FROM ubuntu

WORKDIR /app

COPY . /app/

#Uncomment this if you get "Externally Managed Environmenr" error
ENV PIP_BREAK_SYSTEM_PACKAGES 1

RUN apt-get update && \
    apt-get install -y python3 python3-pip && \
    pip install -r requirements.txt

ENTRYPOINT [ "python3" ]
CMD [ "manage.py", "runserver", "0.0.0.0:8000" ]
